---
theme: default    # not supported

player:    # not supported
    song_id: 0
    position: 0
    playback_mode: 4
    state: 0

plugin:
    NetEaseMusic: true
    MprisEx: true
    Hotkey: true
    LocalSong: true

lyric:
    color: default    # not supported
    background: default

songs:
    dirs: [~/Music]
    download: ~/Music

width: 960
height: 600
...
